model: "Qwen/Qwen3-Next-80B-A3B-Instruct"
model_local_dir: "/scratch/06782/ysu707/models/qwen3_next_80b_a3b_instr"
backend: ds_zero3
ds_config_path: inference_multinode/ds_zero3_inference.json

dataset: sts22_crosslingual
out_dir: /work/06782/ysu707/ls6/PRLE/results/sts22_crosslingual/qwen3_next_80b_a3b_instr/five_shot
limit: null
icl_n: 5

max_new_tokens: 10
temperature: 0.0
batch_size: 64

dtype: bfloat16
max_length: 512
cache_dir: /scratch/06782/ysu707/prle_cache/hf

heartbeat_every: 200
